/* ============================================
   ZEFFER SQUIN GROUP — data.js
   All static data: divisions, nav, stats
   ============================================ */

const DIVISIONS = [
  {
    id: "ra-guard", code: "ZS-01",
    name: "Ra Guard",
    tagline: "Cyber Security & IT Solutions",
    headline: "Fortify Your Digital Future",
    color: "#0CF2A0", dim: "#020D08",
    icon: "🛡️",
    heroText: "Enterprise-grade protection for the digital age. Ra Guard delivers comprehensive cybersecurity solutions trusted by corporations, governments, and critical infrastructure worldwide.",
    about: "Founded as the first division of Zeffer Squin Group, Ra Guard has grown into a premier cybersecurity and IT solutions provider. With a team of certified ethical hackers, network engineers, and compliance specialists, we stand as the last line of defence against an ever-evolving threat landscape.",
    services: [
      { name: "Penetration Testing",    desc: "Simulate real-world attacks to expose vulnerabilities before adversaries do." },
      { name: "SOC-as-a-Service",       desc: "24/7 Security Operations Center monitoring with elite threat analysts." },
      { name: "Cloud Security",         desc: "Secure AWS, Azure, and GCP environments from misconfigurations and breaches." },
      { name: "IT Infrastructure",      desc: "Design and deploy resilient, scalable enterprise networks." },
      { name: "Incident Response",      desc: "Rapid containment, eradication, and recovery from cyber incidents." },
      { name: "Compliance Consulting",  desc: "Navigate ISO 27001, SOC 2, GDPR, and regional frameworks." },
    ],
    stats: [
      { v: "200+", l: "Clients Protected" },
      { v: "99.9%", l: "Threat Detection" },
      { v: "24/7",  l: "SOC Monitoring" },
      { v: "0",     l: "Breaches Undetected" },
    ],
  },
  {
    id: "guest-house", code: "ZS-02",
    name: "Guest House",
    tagline: "Hospitality & Accommodation",
    headline: "Where Comfort Meets Distinction",
    color: "#F5C842", dim: "#0D0B02",
    icon: "🏡",
    heroText: "Premium hospitality redefined. Our properties blend sophisticated design with heartfelt service, creating sanctuaries for business travellers and leisure guests alike.",
    about: "Zeffer Squin Guest House operates a curated portfolio of premium accommodation properties. Each location is thoughtfully designed to provide an unparalleled experience — combining the warmth of boutique hospitality with the reliability of a world-class brand.",
    services: [
      { name: "Premium Rooms & Suites", desc: "Elegantly appointed rooms with premium bedding, amenities, and technology." },
      { name: "Event & Function Spaces", desc: "Versatile venues for conferences, seminars, and private celebrations." },
      { name: "Business Suites",         desc: "Fully equipped executive suites with dedicated workspaces and concierge." },
      { name: "F&B Services",            desc: "Curated dining experiences from breakfast through late-night service." },
      { name: "Concierge Services",      desc: "Personalised local expertise, transport, and itinerary planning." },
      { name: "Long-Stay Packages",      desc: "Extended residency options with monthly rates and homely comforts." },
    ],
    stats: [
      { v: "50+",  l: "Rooms & Suites" },
      { v: "4.9★", l: "Guest Rating" },
      { v: "8+",   l: "Years Operating" },
      { v: "98%",  l: "Occupancy Peak" },
    ],
  },
  {
    id: "global-supply", code: "ZS-03",
    name: "Global Supply",
    tagline: "International Trade & Logistics",
    headline: "Bridging Markets Worldwide",
    color: "#FF6B6B", dim: "#0D0303",
    icon: "🌐",
    heroText: "Your gateway to global commerce. We source, import, and deliver premium products from 40+ nations with precision logistics and uncompromising quality standards.",
    about: "Zeffer Squin Global Supply is a full-service international trade and logistics company. Leveraging deep relationships with suppliers across four continents, we enable businesses to access world-class products with streamlined customs, compliance, and delivery.",
    services: [
      { name: "Import Solutions",       desc: "End-to-end import management from procurement to final delivery." },
      { name: "Export Facilitation",    desc: "Connect Indonesian producers with international buyers efficiently." },
      { name: "Supply Chain Mgmt",      desc: "Optimise your entire supply chain for cost, speed, and resilience." },
      { name: "Customs Brokerage",      desc: "Expert handling of customs documentation and regulatory compliance." },
      { name: "Warehousing",            desc: "Strategic warehousing solutions with inventory management systems." },
      { name: "Quality Control",        desc: "Rigorous pre-shipment inspection and quality assurance protocols." },
    ],
    stats: [
      { v: "40+",   l: "Partner Nations" },
      { v: "1,000+",l: "Products Sourced" },
      { v: "98%",   l: "On-Time Delivery" },
      { v: "500+",  l: "Trade Partners" },
    ],
  },
  {
    id: "tech-ventures", code: "ZS-04",
    name: "Tech Ventures",
    tagline: "Innovation & Digital Products",
    headline: "Building Tomorrow, Today",
    color: "#818CF8", dim: "#03030D",
    icon: "⚡",
    heroText: "Where bold ideas become market-ready products. Tech Ventures invests in, builds, and scales digital innovations that define the next generation of business.",
    about: "Zeffer Squin Tech Ventures is the innovation engine of the group. We combine strategic investment capital with hands-on product development expertise to create, launch, and scale transformative technology solutions across SaaS, AI, and digital platforms.",
    services: [
      { name: "Software Development",  desc: "Custom web and mobile applications built for scale and performance." },
      { name: "SaaS Products",          desc: "Proprietary software-as-a-service platforms serving global markets." },
      { name: "Startup Investment",     desc: "Early-stage capital and strategic support for tech startups." },
      { name: "Digital Strategy",       desc: "Technology roadmaps and digital transformation consulting." },
      { name: "UI/UX Design",           desc: "Human-centred design that drives engagement and conversion." },
      { name: "AI Integration",         desc: "Embed artificial intelligence into products and business workflows." },
    ],
    stats: [
      { v: "20+", l: "Products Launched" },
      { v: "15+", l: "Startups Backed" },
      { v: "$5M+",l: "Portfolio Value" },
      { v: "3",   l: "AI Products Live" },
    ],
  },
  {
    id: "zs-property", code: "ZS-05",
    name: "ZS Property",
    tagline: "Real Estate & Development",
    headline: "Building Value, Shaping Skylines",
    color: "#34D399", dim: "#020D07",
    icon: "🏢",
    heroText: "Strategic real estate development and investment management. We create spaces that inspire living, working, and thriving — delivering long-term value for investors and communities.",
    about: "ZS Property is the real estate arm of Zeffer Squin Group, responsible for residential, commercial, and mixed-use property development. With a disciplined investment approach and strong development capabilities, we deliver projects that stand the test of time.",
    services: [
      { name: "Residential Development",desc: "Design and develop premium housing projects for modern living." },
      { name: "Commercial Spaces",       desc: "Office parks, retail centres, and mixed-use commercial developments." },
      { name: "Property Management",     desc: "Professional management of residential and commercial portfolios." },
      { name: "Investment Advisory",     desc: "Data-driven real estate investment analysis and advisory services." },
      { name: "Architectural Design",    desc: "In-house design capability for distinctive, functional spaces." },
      { name: "Leasing & Sales",         desc: "End-to-end leasing and property sales management." },
    ],
    stats: [
      { v: "30+",     l: "Projects Completed" },
      { v: "500K+",   l: "sqm Developed" },
      { v: "IDR 2T+", l: "Portfolio Value" },
      { v: "95%",     l: "Occupancy Rate" },
    ],
  },
  {
    id: "zs-consulting", code: "ZS-06",
    name: "ZS Consulting",
    tagline: "Business & Strategy Consulting",
    headline: "Strategic Intelligence, Decisive Action",
    color: "#FB923C", dim: "#0D0602",
    icon: "📊",
    heroText: "Transformative consulting for ambitious organisations. We combine deep industry expertise with rigorous analytical frameworks to help leaders navigate complexity and accelerate growth.",
    about: "ZS Consulting is the strategic advisory division of Zeffer Squin Group, serving C-suite executives, government agencies, and fast-growth companies. Our consultants bring international experience and a results-first mindset to every engagement.",
    services: [
      { name: "Strategy Development",      desc: "Craft winning corporate, business unit, and functional strategies." },
      { name: "Market Entry",              desc: "Research, plan, and execute successful entries into new markets." },
      { name: "M&A Advisory",             desc: "Due diligence, valuation, and integration support for M&A transactions." },
      { name: "Operations Optimization",  desc: "Redesign processes to eliminate waste and boost efficiency." },
      { name: "Risk Management",          desc: "Identify, quantify, and mitigate enterprise-wide risks." },
      { name: "Executive Coaching",       desc: "Develop high-performing leadership teams and organisational culture." },
    ],
    stats: [
      { v: "100+", l: "Engagements" },
      { v: "40+",  l: "Industries Served" },
      { v: "92%",  l: "Client Retention" },
      { v: "3.5×", l: "Avg ROI Delivered" },
    ],
  },
];

const SITE_STATS = [
  { v: "2016",  l: "Established" },
  { v: "6+",    l: "Divisions" },
  { v: "40+",   l: "Nations" },
  { v: "1,200+",l: "Clients" },
  { v: "500+",  l: "Professionals" },
];

const CONTACT_INFO = [
  { label: "General Inquiry",    val: "info@zeffersquin.com",    sub: "We respond within 24 hours",         color: "#0CF2A0" },
  { label: "WhatsApp Business",  val: "+62 xxx-xxxx-xxxx",       sub: "Available Mon–Sat, 9AM–6PM WIB",    color: "#F5C842" },
  { label: "LinkedIn",           val: "Zeffer Squin Group",      sub: "Connect & follow us",                color: "#818CF8" },
  { label: "Headquarters",       val: "Jakarta, Indonesia",       sub: "Southeast Asia HQ",                  color: "#FF6B6B" },
];
